// ============================================================
// CONCOURS MAROC — Base de données et Seed Réel
// Institutions, universités, ministères réels avec logos officiels
// ============================================================

import type { Competition, Course, DocItem, Exam, Ministry, School, University, User, AppNotification } from './types';
import { daysAgo, daysFromNow, hashPassword } from './utils';
import { REAL_MINISTRIES, REAL_UNIVERSITIES, REAL_SCHOOLS } from '../data/institutionsData';
import { resolveInstitutionLogo } from '../data/institutionLogos';

export const SEED_MINISTRIES: Ministry[] = REAL_MINISTRIES;
export const SEED_UNIVERSITIES: University[] = REAL_UNIVERSITIES;
export const SEED_SCHOOLS: School[] = REAL_SCHOOLS;

interface CSeed {
  id: string; slug: string; title: string; org: string; orgType: 'MINISTERE' | 'ECOLE' | 'INSTITUTION';
  schoolId?: string; ministryId?: string; universityId?: string; category: Competition['category'];
  year: number; level: string; city: string; region: string; domaine?: string; places: number;
  deadlineIn: number | null; startIn: number; examIn: number | null; color: string;
  verified: boolean; publishedDaysAgo: number; publishStatus?: Competition['publishStatus'];
  registrationUrl?: string; website?: string; manualStatus?: Competition['manualStatus'];
  description: string; conditions: string[]; matieres: string[]; epreuves: string[];
}

const C: CSeed[] = [
  // ================= MINISTÈRES =================
  {
    id: 'c1',
    slug: 'concours-recrutement-enseignants-2026',
    title: 'Concours de recrutement des cadres enseignants (AREF)',
    org: "Ministère de l'Éducation Nationale, du Préscolaire et des Sports",
    orgType: 'MINISTERE',
    ministryId: 'min-education',
    category: 'MINISTERE',
    year: 2026,
    level: 'Bac+3 (Licence)',
    city: 'Rabat',
    region: 'Toutes les régions',
    domaine: 'Éducation & Enseignement',
    places: 20000,
    deadlineIn: 22,
    startIn: -8,
    examIn: 45,
    color: '#1B5E20',
    verified: true,
    publishedDaysAgo: 8,
    registrationUrl: 'https://tawdif.men.gov.ma',
    website: 'https://www.men.gov.ma',
    description: "Recrutement des cadres enseignants du cycle primaire et secondaire (collégial et qualifiant) au titre de l'année 2026.",
    conditions: [
      'Nationalité marocaine',
      'Être titulaire d’une Licence d’éducation, Licence fondamentale ou équivalent',
      'Âge ne dépassant pas 30 ans à la date du concours',
      'Jouir de ses droits civiques et aptitude physique',
    ],
    matieres: ['Spécialité disciplinaire', 'Didactique de la matière', 'Sciences de l’éducation'],
    epreuves: ['Épreuve écrite de spécialité et didactique (4h)', 'Entretien oral devant jury professionnel'],
  },
  {
    id: 'c2',
    slug: 'concours-administrateurs-interieur-2026',
    title: 'Concours de recrutement des administrateurs 2ème et 3ème grade',
    org: "Ministère de l'Intérieur",
    orgType: 'MINISTERE',
    ministryId: 'min-interieur',
    category: 'MINISTERE',
    year: 2026,
    level: 'Bac+3 / Bac+5',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Administration publique',
    places: 450,
    deadlineIn: 35,
    startIn: 2,
    examIn: 75,
    color: '#B71C1C',
    verified: true,
    publishedDaysAgo: 4,
    manualStatus: 'Bientot',
    registrationUrl: 'https://concours.interieur.gov.ma',
    website: 'https://www.interieur.gov.ma',
    description: 'Recrutement d’administrateurs territoriaux pour les services centraux et préfectures provinciales.',
    conditions: [
      'Nationalité marocaine',
      'Master, DESA ou Licence en Droit public, Sciences politiques, Économie ou Gestion',
      'Âgé de 18 ans au moins et de 45 ans au plus',
    ],
    matieres: ['Droit administratif & constitutionnel', 'Politiques publiques', 'Culture générale'],
    epreuves: ['Épreuve écrite portant sur un sujet d’ordre général (3h)', 'Épreuve de spécialité administrative (3h)', 'Entretien oral'],
  },
  {
    id: 'c3',
    slug: 'concours-medecins-generalistes-2026',
    title: 'Concours de recrutement des médecins généralistes et pharmaciens',
    org: 'Ministère de la Santé et de la Protection Sociale',
    orgType: 'MINISTERE',
    ministryId: 'min-sante',
    category: 'MINISTERE',
    year: 2026,
    level: 'Doctorat (Bac+6/7)',
    city: 'Rabat',
    region: 'Toutes les régions',
    domaine: 'Santé publique',
    places: 1500,
    deadlineIn: 18,
    startIn: -12,
    examIn: 40,
    color: '#0277BD',
    verified: true,
    publishedDaysAgo: 6,
    registrationUrl: 'https://sante.gov.ma/concours',
    website: 'https://www.sante.gov.ma',
    description: 'Recrutement de médecins généralistes de 1er grade pour affectation dans les réseaux hospitaliers et centres de santé.',
    conditions: [
      'Nationalité marocaine',
      'Doctorat en médecine générale ou diplôme reconnu équivalent',
      'Inscription au tableau de l’Ordre National des Médecins',
    ],
    matieres: ['Médecine clinique', 'Santé publique et urgences'],
    epreuves: ['Examen des titres et travaux (Dossier)', 'Entretien oral avec commission médicale'],
  },
  {
    id: 'c7',
    slug: 'concours-inspecteurs-finances-2026',
    title: 'Concours d’inspecteurs des finances et inspecteurs des impôts',
    org: "Ministère de l'Économie et des Finances",
    orgType: 'MINISTERE',
    ministryId: 'min-finances',
    category: 'MINISTERE',
    year: 2026,
    level: 'Bac+5 (Master / Ingénieur)',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Finances & Fiscalité',
    places: 320,
    deadlineIn: 28,
    startIn: -4,
    examIn: 65,
    color: '#0D47A1',
    verified: true,
    publishedDaysAgo: 5,
    registrationUrl: 'https://finances.gov.ma/recrutement',
    website: 'https://www.finances.gov.ma',
    description: 'Recrutement d’inspecteurs pour la Direction Générale des Impôts, la Douane et l’Inspection Générale des Finances.',
    conditions: [
      'Titulaire d’un Master en Économie, Finance, Droit des affaires ou diplôme d’ingénieur d’État en informatique/statistique',
      'Âge inférieur ou égal à 45 ans',
    ],
    matieres: ['Finances publiques', 'Fiscalité marocaine', 'Économie monétaire'],
    epreuves: ['Épreuve écrite générale (3h)', 'Épreuve écrite technique de spécialité (3h)', 'Grand Oral'],
  },
  {
    id: 'c6',
    slug: 'concours-greffiers-justice-2026',
    title: 'Concours de recrutement des rédacteurs judiciaires et greffiers',
    org: 'Ministère de la Justice',
    orgType: 'MINISTERE',
    ministryId: 'min-justice',
    category: 'MINISTERE',
    year: 2026,
    level: 'Bac+2 / Bac+3',
    city: 'Rabat',
    region: 'Toutes les régions',
    domaine: 'Justice & Droit',
    places: 500,
    deadlineIn: 16,
    startIn: -10,
    examIn: 42,
    color: '#5D4037',
    verified: true,
    publishedDaysAgo: 7,
    registrationUrl: 'https://drh.justice.gov.ma/concours',
    website: 'https://www.justice.gov.ma',
    description: 'Recrutement des secrétaires greffiers et rédacteurs judiciaires de 3ème grade pour les cours et tribunaux du Royaume.',
    conditions: [
      'Diplôme d’études universitaires générales (DEUG) en droit ou Licence en études fondamentales (Droit privé/public)',
      'Nationalité marocaine',
    ],
    matieres: ['Organisation judiciaire du Maroc', 'Procédure civile et pénale', 'Français juridique'],
    epreuves: ['QCM de présélection', 'Épreuve écrite juridique (3h)', 'Entretien oral'],
  },
  {
    id: 'c8',
    slug: 'concours-ingenieurs-equipement-2026',
    title: 'Concours de recrutement d’Ingénieurs d’État 1er grade',
    org: "Ministère de l'Équipement et de l'Eau",
    orgType: 'MINISTERE',
    ministryId: 'min-equipement',
    category: 'MINISTERE',
    year: 2026,
    level: 'Bac+5 (Ingénieur d’État)',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Génie Civil & Eau',
    places: 180,
    deadlineIn: 24,
    startIn: -7,
    examIn: 55,
    color: '#01579B',
    verified: true,
    publishedDaysAgo: 6,
    registrationUrl: 'https://equipement.gov.ma/concours',
    website: 'https://www.equipement.gov.ma',
    description: 'Recrutement d’ingénieurs d’État en Génie Civil, Hydraulique, BTP et SIG pour le suivi des grands projets d’infrastructures.',
    conditions: [
      'Diplôme d’ingénieur d’État (EHTP, EMI, ENSA ou équivalent reconnu)',
      'Spécialités : Génie Civil, Ressources en eau, Géotechnique',
    ],
    matieres: ['Ouvrages d’art et voiries', 'Hydraulique et barrages', 'Gestion de projets BTP'],
    epreuves: ['Épreuve écrite technique de spécialité (4h)', 'Entretien oral avec commission d’experts'],
  },

  // ================= GRANDES ÉCOLES D'INGÉNIEURS (CNC & POST-BAC) =================
  {
    id: 'c13',
    slug: 'concours-ensa-maroc-1ere-annee-2026',
    title: 'Concours commun d’accès en 1ère année du réseau ENSA Maroc',
    org: 'ENSA Marrakech — Réseau National ENSA',
    orgType: 'ECOLE',
    schoolId: 'ec-ensa-marrakech',
    universityId: 'univ-uca',
    category: 'ECOLE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Marrakech',
    region: 'National (12 villes)',
    domaine: 'Sciences de l’Ingénieur',
    places: 4200,
    deadlineIn: 30,
    startIn: -15,
    examIn: 60,
    color: '#C62828',
    verified: true,
    publishedDaysAgo: 9,
    registrationUrl: 'https://www.ensa-maroc.ac.ma',
    website: 'https://www.ensa-maroc.ac.ma',
    description: "Concours commun d'accès aux 12 ENSA du Maroc (Marrakech, Agadir, Tanger, Oujda, Fès, Kénitra, Safi, Al Hoceima, Khouribga, El Jadida, Berrechid, Béni Mellal).",
    conditions: [
      'Titulaire ou candidat au Baccalauréat sciences mathématiques ou sciences expérimentales ou sciences et technologies',
      'Présélection sur la base des notes du Baccalauréat national (75%) et régional (25%)',
    ],
    matieres: ['Mathématiques', 'Physique-Chimie'],
    epreuves: ['QCM Mathématiques (1h30)', 'QCM Physique-Chimie (1h30)'],
  },
  {
    id: 'c14',
    slug: 'concours-emi-rabat-cycle-ingenieur-2026',
    title: 'Concours d’accès au Cycle Ingénieur — École Mohammadia d’Ingénieurs',
    org: 'EMI — École Mohammadia d’Ingénieurs',
    orgType: 'ECOLE',
    schoolId: 'ec-emi',
    universityId: 'univ-um5',
    category: 'ECOLE',
    year: 2026,
    level: 'Bac+2 (CPGE / DEUG / DEUST)',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Ingénierie polytechnique',
    places: 350,
    deadlineIn: 20,
    startIn: -20,
    examIn: 48,
    color: '#0D47A1',
    verified: true,
    publishedDaysAgo: 10,
    registrationUrl: 'https://www.emi.ac.ma/concours',
    website: 'https://www.emi.ac.ma',
    description: "Accès à l'EMI Rabat pour les élèves de CPGE (via CNC) et les titulaires de DEUG/DEUST/Licence scientifique (concours sur titre et épreuves).",
    conditions: [
      'Élèves de CPGE admissibles au Concours National Commun (CNC)',
      'Pour les passerelles : Titulaires d’un DEUG/DEUST avec mention Bien ou Très Bien, âgés de moins de 23 ans',
    ],
    matieres: ['Mathématiques', 'Physique', 'Sciences Industrielles', 'Français/Anglais'],
    epreuves: ['Épreuves écrites du CNC ou épreuves spécifiques passerelles', 'Visite médicale d’aptitude militaire', 'Entretien oral'],
  },
  {
    id: 'c22',
    slug: 'concours-ensias-rabat-ingenieur-2026',
    title: 'Concours d’accès à l’ENSIAS Rabat (Informatique & IA)',
    org: 'ENSIAS — Université Mohammed V',
    orgType: 'ECOLE',
    schoolId: 'ec-ensias',
    universityId: 'univ-um5',
    category: 'ECOLE',
    year: 2026,
    level: 'Bac+2 / Bac+3',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Intelligence Artificielle & Logiciel',
    places: 280,
    deadlineIn: 25,
    startIn: -10,
    examIn: 52,
    color: '#005A9C',
    verified: true,
    publishedDaysAgo: 5,
    registrationUrl: 'http://ensias.um5.ac.ma/concours',
    website: 'http://ensias.um5.ac.ma',
    description: "Accès au cycle ingénieur de l'ENSIAS : Intelligence Artificielle, Cybersécurité, Génie Logiciel, Data Science et IoT.",
    conditions: [
      'Admissibilité CNC pour les classes prépas',
      'Pour les passerelles universitaires : Licence SMI/SMA ou DUT Informatique avec mention',
    ],
    matieres: ['Mathématiques appliquées', 'Algorithmique & Structures de données', 'Anglais technique'],
    epreuves: ['Écrit CNC ou épreuves d’algorithmique et mathématiques (passerelles)', 'Entretien technique'],
  },
  {
    id: 'c21',
    slug: 'concours-ehtp-casablanca-ingenieur-2026',
    title: 'Concours d’admission au cycle ingénieur — EHTP Casablanca',
    org: 'EHTP — École Hassania des Travaux Publics',
    orgType: 'ECOLE',
    schoolId: 'ec-ehtp',
    ministryId: 'min-equipement',
    category: 'ECOLE',
    year: 2026,
    level: 'Bac+2 / Bac+3',
    city: 'Casablanca',
    region: 'Casablanca-Settat',
    domaine: 'Génie Civil & Infrastructures',
    places: 300,
    deadlineIn: 21,
    startIn: -15,
    examIn: 46,
    color: '#01579B',
    verified: true,
    publishedDaysAgo: 7,
    registrationUrl: 'https://www.ehtp.ac.ma/concours',
    website: 'https://www.ehtp.ac.ma',
    description: "Admission à l'École Hassania des Travaux Publics pour les filières Génie Civil, Hydraulique, SIG et Informatique.",
    conditions: [
      'Élèves de CPGE via le Concours National Commun (filières MP, PSI, TSI)',
      'Titulaires d’une Licence scientifique en Sciences Mathématiques ou Physique (passerelles)',
    ],
    matieres: ['Mathématiques', 'Physique', 'Mécanique des structures'],
    epreuves: ['Épreuves écrites CNC', 'Épreuves spécifiques passerelles universitaires', 'Entretien oral'],
  },
  {
    id: 'c15',
    slug: 'concours-ensam-maroc-1ere-annee-2026',
    title: 'Concours d’accès en 1ère année des ENSAM (Meknès & Casablanca)',
    org: 'ENSAM Meknès — Université Moulay Ismaïl',
    orgType: 'ECOLE',
    schoolId: 'ec-ensam-meknes',
    universityId: 'univ-umi',
    category: 'ECOLE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Meknès',
    region: 'Fès-Meknès',
    domaine: 'Génie Mécanique & Industriel',
    places: 600,
    deadlineIn: 28,
    startIn: -12,
    examIn: 58,
    color: '#4A148C',
    verified: true,
    publishedDaysAgo: 7,
    registrationUrl: 'http://www.ensam-umi.ac.ma',
    website: 'http://www.ensam-umi.ac.ma',
    description: "Concours commun d'accès en première année aux ENSAM de Meknès et Casablanca (Cycle préparatoire intégré).",
    conditions: [
      'Baccalauréat scientifique ou technique industriel',
      'Seuil de présélection national calculé sur les notes du bac',
    ],
    matieres: ['Mathématiques', 'Physique', 'Sciences de l’ingénieur'],
    epreuves: ['QCM Mathématiques (1h30)', 'QCM Physique et Sciences industrielles (1h30)'],
  },
  {
    id: 'c16',
    slug: 'concours-inpt-cycle-ingenieur-2026',
    title: 'Concours d’admission au cycle ingénieur de l’INPT Rabat',
    org: 'INPT — Institut National des Postes et Télécommunications',
    orgType: 'ECOLE',
    schoolId: 'ec-inpt',
    ministryId: 'min-numerique',
    category: 'ECOLE',
    year: 2026,
    level: 'Bac+2 / Bac+3',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Télécoms & Cybersécurité',
    places: 220,
    deadlineIn: 15,
    startIn: -22,
    examIn: 38,
    color: '#00695C',
    verified: true,
    publishedDaysAgo: 11,
    registrationUrl: 'https://www.inpt.ac.ma/concours',
    website: 'https://www.inpt.ac.ma',
    description: "Admission à l'INPT Rabat dans les filières Cybersécurité, Cloud Computing, Data Science, Réseaux et Télécoms.",
    conditions: [
      'Candidats CPGE (CNC)',
      'Passerelles : Titulaires d’une Licence SMI/SMA ou DEUG avec mention',
    ],
    matieres: ['Mathématiques', 'Algorithmique & Programmation', 'Anglais'],
    epreuves: ['Écrit de présélection pour candidats universitaires', 'Entretien de motivation et de logique'],
  },

  // ================= COMMERCE & GESTION (ENCG & ISCAE) =================
  {
    id: 'c17',
    slug: 'concours-tafem-encg-maroc-2026',
    title: 'TAFEM 2026 — Concours commun d’accès aux 12 ENCG du Maroc',
    org: 'ENCG Settat — Réseau National ENCG',
    orgType: 'ECOLE',
    schoolId: 'ec-encg-settat',
    universityId: 'univ-uh1',
    category: 'ECOLE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Settat',
    region: 'National (12 campus)',
    domaine: 'Commerce & Gestion',
    places: 4500,
    deadlineIn: 32,
    startIn: -10,
    examIn: 62,
    color: '#1565C0',
    verified: true,
    publishedDaysAgo: 8,
    registrationUrl: 'https://tafem.ma',
    website: 'https://tafem.ma',
    description: "Test d'Admissibilité à la Formation En Management (TAFEM) pour l'accès aux 12 ENCG (Settat, Casa, Tanger, Agadir, Marrakech, Fès, Kénitra, Oujda, El Jadida, Dakhla, Béni Mellal, Meknès).",
    conditions: [
      'Baccalauréat en Sciences Économiques, Gestion Comptable, Sciences Maths ou Sciences Expérimentales',
      'Calcul du seuil d’admissibilité basé sur les notes du baccalauréat',
    ],
    matieres: ['Sous-test 1 : Mémorisation et compréhension', 'Sous-test 2 : Logique et mathématiques', 'Sous-test 3 : Culture générale', 'Sous-test 4 : Anglais'],
    epreuves: ['Épreuve QCM TAFEM d’une durée de 2 heures portant sur les 4 sous-tests'],
  },
  {
    id: 'c23',
    slug: 'concours-iscae-grande-ecole-2026',
    title: 'Concours National d’accès à la Grande École du Groupe ISCAE',
    org: 'Groupe ISCAE (Casablanca & Rabat)',
    orgType: 'ECOLE',
    schoolId: 'ec-iscae',
    ministryId: 'min-industrie',
    category: 'ECOLE',
    year: 2026,
    level: 'Bac+2 (CPGE ECT/ECS ou DEUG)',
    city: 'Casablanca',
    region: 'Casablanca-Settat',
    domaine: 'Management & Finance',
    places: 380,
    deadlineIn: 45,
    startIn: 5,
    examIn: 85,
    color: '#E65100',
    verified: true,
    publishedDaysAgo: 3,
    manualStatus: 'Bientot',
    registrationUrl: 'https://www.iscae.ma/candidature',
    website: 'https://www.iscae.ma',
    description: "Concours d'accès au Programme Grande École (Diplôme ISCAE grade Master) à Casablanca et Rabat.",
    conditions: [
      'Élèves de CPGE économiques et commerciales (ECT / ECS)',
      'Étudiants d’universités titulaires d’un DEUG en économie/gestion avec au moins 3 mentions',
    ],
    matieres: ['Mathématiques financières & appliquées', 'Dissertation de culture générale', 'Épreuve d’anglais', 'Épreuve d’arabe'],
    epreuves: ['4 épreuves écrites d’admissibilité', 'Entretien individuel devant jury de chefs d’entreprise', 'Épreuve orale d’anglais'],
  },

  // ================= SANTÉ, ARCHITECTURE, AGRONOMIE =================
  {
    id: 'c24',
    slug: 'concours-ena-architecture-maroc-2026',
    title: 'Concours commun d’accès aux Écoles Nationales d’Architecture (ENA)',
    org: 'ENA Rabat — Écoles Nationales d’Architecture',
    orgType: 'ECOLE',
    schoolId: 'ec-ena',
    ministryId: 'min-sup',
    category: 'ECOLE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Rabat',
    region: 'National (Rabat, Marrakech, Fès, Tétouan, Agadir, Oujda)',
    domaine: 'Architecture & Urbanisme',
    places: 480,
    deadlineIn: 38,
    startIn: 0,
    examIn: 70,
    color: '#8D6E63',
    verified: true,
    publishedDaysAgo: 4,
    manualStatus: 'Bientot',
    registrationUrl: 'http://concoursena.ma',
    website: 'http://www.archi.ac.ma',
    description: "Concours d'accès aux Écoles Nationales d'Architecture du Maroc (ENA Rabat, Marrakech, Fès, Tétouan, Agadir et Oujda).",
    conditions: [
      'Baccalauréat scientifique, technique ou économique avec mention Très Bien ou Bien',
      'Présélection sur la base de la moyenne du Baccalauréat',
    ],
    matieres: ['Dessin d’observation & représentation', 'Expression écrite en français', 'Culture générale'],
    epreuves: ['Épreuve écrite de dessin (2h)', 'Épreuve d’analyse de texte et culture générale (1h30)'],
  },
  {
    id: 'c25',
    slug: 'concours-ispits-maroc-paramedical-2026',
    title: 'Concours d’accès aux Instituts ISPITS du Ministère de la Santé',
    org: 'ISPITS Rabat — Ministère de la Santé',
    orgType: 'ECOLE',
    schoolId: 'ec-ispits-rabat',
    ministryId: 'min-sante',
    category: 'ECOLE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Rabat',
    region: 'National (Toutes régions)',
    domaine: 'Professions de Santé & Soins',
    places: 6500,
    deadlineIn: 26,
    startIn: -10,
    examIn: 54,
    color: '#0277BD',
    verified: true,
    publishedDaysAgo: 7,
    registrationUrl: 'https://ispits.sante.gov.ma',
    website: 'https://ispits.sante.gov.ma',
    description: "Accès au cycle de la Licence professionnelle dans les ISPITS : Infirmier Polyvalent, Sage-Femme, Radiologie, Anesthésie, Laboratoire et Rééducation.",
    conditions: [
      'Titulaire du Baccalauréat Sciences Expérimentales (SVT, PC) ou Sciences Mathématiques',
      'Présélection basée sur la formule officielle du Ministère de la Santé',
    ],
    matieres: ['Sciences de la Vie et de la Terre (SVT)', 'Chimie', 'Langue française'],
    epreuves: ['Épreuve écrite sous forme de QCM (2h)', 'Test d’aptitude pour certaines options'],
  },
  {
    id: 'c26',
    slug: 'concours-commun-facultes-medecine-maroc-2026',
    title: 'Concours commun d’accès aux Facultés de Médecine, Pharmacie et Dentaire',
    org: 'FMPR — Facultés de Médecine et de Pharmacie du Maroc',
    orgType: 'ECOLE',
    schoolId: 'ec-fmpr',
    universityId: 'univ-um5',
    category: 'UNIVERSITE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Rabat',
    region: 'National (Toutes les facultés)',
    domaine: 'Médecine, Pharmacie & Dentaire',
    places: 5200,
    deadlineIn: 40,
    startIn: 4,
    examIn: 78,
    color: '#0B2A4A',
    verified: true,
    publishedDaysAgo: 2,
    manualStatus: 'Bientot',
    registrationUrl: 'https://cursus.enssup.gov.ma',
    website: 'https://www.enssup.gov.ma',
    description: "Concours commun national d'accès en 1ère année des études médicales, pharmaceutiques et odontologiques dans toutes les facultés de médecine publiques du Royaume.",
    conditions: [
      'Titulaire ou futur bachelier en Sciences Mathématiques ou Sciences Expérimentales',
      'Seuil de présélection unifié calculé sur les notes officielles du bac',
    ],
    matieres: ['Sciences de la Vie et de la Terre', 'Chimie', 'Physique', 'Mathématiques'],
    epreuves: ['QCM unique d’une durée de 3h couvrant les 4 composantes scientifiques'],
  },
  {
    id: 'c18',
    slug: 'concours-apesa-iav-hassan-ii-2026',
    title: 'Concours d’accès à l’APESA — Institut Agronomique et Vétérinaire Hassan II',
    org: 'IAV Hassan II — Ministère de l’Agriculture',
    orgType: 'ECOLE',
    schoolId: 'ec-iav',
    ministryId: 'min-agri',
    category: 'ECOLE',
    year: 2026,
    level: 'Baccalauréat (Bac+0)',
    city: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    domaine: 'Agronomie & Vétérinaire',
    places: 320,
    deadlineIn: 12,
    startIn: -25,
    examIn: 32,
    color: '#2E7D32',
    verified: true,
    publishedDaysAgo: 12,
    registrationUrl: 'https://apesa.iav.ac.ma',
    website: 'https://www.iav.ac.ma',
    description: "Accès à l'Année Préparatoire aux Études Supérieures en Agronomie (APESA) de l'IAV Hassan II à Rabat.",
    conditions: [
      'Baccalauréat Sciences Mathématiques ou Sciences Physiques obtenu avec mention',
      'Âgé de moins de 23 ans au 1er septembre',
    ],
    matieres: ['Mathématiques', 'Physique-Chimie', 'Sciences Naturelles (SVT)'],
    epreuves: ['Sélection sur dossier d’excellence académique et épreuve écrite'],
  },
  {
    id: 'c27',
    slug: 'concours-aiac-aviation-civile-2026',
    title: 'Concours de l’Académie Internationale Mohammed VI de l’Aviation Civile',
    org: 'AIAC Mohammed VI — ONDA',
    orgType: 'ECOLE',
    schoolId: 'ec-aiac',
    ministryId: 'min-equipement',
    category: 'ECOLE',
    year: 2026,
    level: 'Bac+2 (CNC)',
    city: 'Casablanca',
    region: 'Casablanca-Settat',
    domaine: 'Aéronautique & Contrôle Aérien',
    places: 160,
    deadlineIn: 19,
    startIn: -14,
    examIn: 44,
    color: '#0B2A4A',
    verified: true,
    publishedDaysAgo: 8,
    registrationUrl: 'http://www.aiac.ma/concours',
    website: 'http://www.aiac.ma',
    description: "Concours d'accès au Cycle Ingénieur en Génie Aéronautique, Contrôleurs de la Navigation Aérienne (ICNA) et Électroniciens de Sécurité (IESSNA).",
    conditions: [
      'Candidats CPGE MP/PSI admissibles au Concours National Commun (CNC)',
      'Aptitude médicale aéronautique de classe 1 pour la filière ICNA',
    ],
    matieres: ['Mathématiques', 'Physique', 'Anglais aéronautique'],
    epreuves: ['Écrits CNC', 'Visite médicale au Centre d’Expertise Médicale du Personnel Navigant (CEMPN)', 'Entretien oral'],
  },
  {
    id: 'c28',
    slug: 'inscriptions-ofppt-technicien-specialise-2026',
    title: 'Inscriptions et tests d’admission OFPPT — Technicien Spécialisé',
    org: 'OFPPT — Office de la Formation Professionnelle',
    orgType: 'ECOLE',
    schoolId: 'ec-ofppt',
    category: 'FORMATION',
    year: 2026,
    level: 'Niveau Bac / Bacheliers',
    city: 'Casablanca',
    region: 'Toutes les régions (400+ instituts)',
    domaine: 'Formation Professionnelle',
    places: 120000,
    deadlineIn: 42,
    startIn: 1,
    examIn: 80,
    color: '#0B2A4A',
    verified: true,
    publishedDaysAgo: 3,
    manualStatus: 'Bientot',
    registrationUrl: 'https://www.ofppt.ma/inscription',
    website: 'https://www.ofppt.ma',
    description: "Inscriptions ouvertes pour les filières Technicien Spécialisé (Bac+2), Technicien et les Cités des Métiers et des Compétences (CMC).",
    conditions: [
      'Titulaire du Baccalauréat pour le niveau Technicien Spécialisé',
      'Niveau Bac ou 3ème année collège pour le niveau Technicien ou Qualification',
    ],
    matieres: ['Test psychotechnique', 'Français', 'Logique de base'],
    epreuves: ['Test de positionnement informatisé dans les centres ISTA'],
  },
];

export function buildCompetitions(): Competition[] {
  return C.map((c) => {
    const school = c.schoolId ? SEED_SCHOOLS.find(s => s.id === c.schoolId) : undefined;
    const ministry = c.ministryId ? SEED_MINISTRIES.find(m => m.id === c.ministryId) : undefined;
    const university = (c.universityId || school?.universityId) ? SEED_UNIVERSITIES.find(u => u.id === (c.universityId || school?.universityId)) : undefined;

    // Resolve official local logo cleanly using resolveInstitutionLogo
    const logoRes = resolveInstitutionLogo({
      institutionId: c.schoolId || c.ministryId,
      institutionType: c.schoolId ? 'school' : 'ministry',
      universityId: university?.id,
      ministryId: ministry?.id,
      existingLogoUrl: school?.logoUrl || ministry?.logoUrl,
    });
    const logoUrl = logoRes.logoUrl || school?.logoUrl || ministry?.logoUrl;

    return {
      id: c.id,
      slug: c.slug,
      title: c.title,
      organizationName: c.org,
      organizationType: c.orgType,
      schoolId: c.schoolId,
      ministryId: c.ministryId,
      category: c.category,
      year: c.year,
      level: c.level,
      city: c.city,
      region: c.region,
      domaine: c.domaine,
      places: c.places,
      description: c.description,
      conditions: c.conditions,
      profil: 'Candidats marocains motivés, sérieux et répondant aux critères d’éligibilité fixés par l’avis officiel.',
      programme: 'Programme de révision officiel : préparation des matières écrites, épreuves scientifiques/techniques et entraînement oral.',
      matieres: c.matieres,
      epreuves: c.epreuves,
      documentsDemandes: [
        'Copie certifiée conforme de la Carte Nationale d’Identité Électronique (CNIE)',
        'Copie certifiée du Baccalauréat ou du Diplôme requis',
        'Relevés de notes officiels (régional, national ou universitaires)',
        'Attestation de scolarité de l’année en cours',
        'Formulaire de candidature en ligne dûment signé',
      ],
      procedure: '1. Effectuez votre préinscription sur le portail officiel. 2. Téléversez les justificatifs numérisés en format PDF. 3. Validez définitivement avant la date limite. 4. Imprimez votre reçu de dépôt et votre convocation.',
      frais: 'Gratuit pour les concours de la fonction publique et universités publiques marocaines.',
      resultats: 'Les listes des candidats admissibles aux épreuves écrites puis la liste des admis définitifs sont publiées sur le portail officiel.',
      registrationStart: c.startIn >= 0 ? daysFromNow(c.startIn) : daysAgo(-c.startIn),
      registrationDeadline: c.deadlineIn === null ? undefined : c.deadlineIn >= 0 ? daysFromNow(c.deadlineIn) : daysAgo(-c.deadlineIn),
      competitionDate: c.examIn === null ? undefined : c.examIn >= 0 ? daysFromNow(c.examIn) : daysAgo(-c.examIn),
      publishedAt: daysAgo(c.publishedDaysAgo),
      officialWebsite: c.website,
      registrationUrl: c.registrationUrl,
      sourceUrl: c.website,
      sourceOrganization: c.org,
      verificationStatus: c.verified ? 'VERIFIED' : 'PENDING',
      verifiedAt: c.verified ? daysAgo(Math.max(1, c.publishedDaysAgo - 1)) : undefined,
      verifiedBy: c.verified ? 'Équipe Officielle Concours Maroc' : undefined,
      publishStatus: c.publishStatus ?? 'PUBLISHED',
      manualStatus: c.manualStatus,
      logoColor: c.color,
      logoUrl: logoUrl,
      officialLogo: logoUrl,
      views: 850 + Math.floor(Math.random() * 9500),
      isDemo: false,
      createdAt: daysAgo(c.publishedDaysAgo),
      updatedAt: daysAgo(1),
    };
  });
}

export const SEED_EXAMS: Exam[] = [
  { id: 'ex1', slug: 'ensa-maths-2024', title: 'Concours ENSA — Mathématiques', schoolId: 'ec-ensa-marrakech', schoolName: 'ENSA Marrakech', organizationName: 'ENSA Marrakech', subject: 'Mathématiques', year: 2024, level: 'Bac+0', type: 'Concours', description: 'Épreuve officielle de mathématiques du concours commun des ENSA du Maroc.', pages: 8, duration: '1h30', downloads: 8420, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: 'ex2', slug: 'ensa-physique-2024', title: 'Concours ENSA — Physique & Chimie', schoolId: 'ec-ensa-marrakech', schoolName: 'ENSA Marrakech', organizationName: 'ENSA Marrakech', subject: 'Physique', year: 2024, level: 'Bac+0', type: 'Concours', pages: 8, duration: '1h30', downloads: 6890, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(60), updatedAt: daysAgo(5) },
  { id: 'ex3', slug: 'cnc-maths-1-mp-2024', title: 'Concours National Commun (CNC) — Mathématiques I (MP)', schoolId: 'ec-emi', schoolName: 'EMI — Réseau CNC', organizationName: 'EMI', subject: 'Mathématiques', year: 2024, level: 'Bac+2', type: 'Concours', pages: 6, duration: '4h', downloads: 9340, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(90), updatedAt: daysAgo(12) },
  { id: 'ex4', slug: 'tafem-encg-epreuve-2024', title: 'TAFEM — Test d’Admissibilité aux ENCG Maroc', schoolId: 'ec-encg-settat', schoolName: 'ENCG Settat', organizationName: 'ENCG Settat', subject: 'Logique & Gestion', year: 2024, level: 'Bac+0', type: 'Concours', pages: 12, duration: '2h', downloads: 12400, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(50), updatedAt: daysAgo(4) },
  { id: 'ex5', slug: 'inpt-informatique-2023', title: 'Concours Passerelles INPT — Informatique & Algorithmique', schoolId: 'ec-inpt', schoolName: 'INPT Rabat', organizationName: 'INPT Rabat', subject: 'Informatique', year: 2023, level: 'Bac+2', type: 'Concours', pages: 7, duration: '2h', downloads: 3560, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(80), updatedAt: daysAgo(9) },
  { id: 'ex6', slug: 'iav-biologie-chimie-2024', title: 'Concours APESA IAV Hassan II — SVT & Chimie', schoolId: 'ec-iav', schoolName: 'IAV Hassan II', organizationName: 'IAV Hassan II', subject: 'SVT', year: 2024, level: 'Bac+0', type: 'Concours', pages: 6, duration: '2h', downloads: 4170, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(40), updatedAt: daysAgo(6) },
  { id: 'ex7', slug: 'ensam-maths-physique-2024', title: 'Concours ENSAM — Mathématiques & Sciences Industrielles', schoolId: 'ec-ensam-meknes', schoolName: 'ENSAM Meknès', organizationName: 'ENSAM Meknès', subject: 'Mathématiques', year: 2024, level: 'Bac+0', type: 'Concours', pages: 8, duration: '2h', downloads: 5820, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(55), updatedAt: daysAgo(7) },
  { id: 'ex8', slug: 'recrutement-enseignants-specialite-2024', title: 'Concours Enseignants (AREF) — Épreuve de spécialité Maths', ministryId: 'min-education', schoolName: "Ministère de l'Éducation Nationale", organizationName: "Ministère de l'Éducation Nationale", subject: 'Mathématiques & Didactique', year: 2024, level: 'Bac+3', type: 'Recrutement', pages: 10, duration: '4h', downloads: 14890, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(100), updatedAt: daysAgo(15) },
  { id: 'ex9', slug: 'iscae-epreuve-anglais-2024', title: 'Concours Grande École ISCAE — Anglais & Business Essay', schoolId: 'ec-iscae', schoolName: 'ISCAE', organizationName: 'ISCAE', subject: 'Anglais', year: 2024, level: 'Bac+2', type: 'Concours', pages: 5, duration: '1h30', downloads: 4980, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(45), updatedAt: daysAgo(3) },
  { id: 'ex10', slug: 'fmp-concours-medecine-2024', title: 'Concours Commun Facultés de Médecine & Pharmacie (FMP)', schoolId: 'ec-fmpr', schoolName: 'FMP Rabat', organizationName: 'FMP Rabat', subject: 'SVT & Chimie', year: 2024, level: 'Bac+0', type: 'Concours', pages: 12, duration: '3h', downloads: 18750, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(120), updatedAt: daysAgo(20) },
  { id: 'ex11', slug: 'ehtp-passerelles-physique-2024', title: 'Concours Passerelles EHTP — Résistance des Matériaux & Physique', schoolId: 'ec-ehtp', schoolName: 'EHTP Casablanca', organizationName: 'EHTP Casablanca', subject: 'Physique & Mécanique', year: 2024, level: 'Bac+2', type: 'Concours', pages: 7, duration: '3h', downloads: 2940, hasCorrection: false, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(110), updatedAt: daysAgo(18) },
  { id: 'ex12', slug: 'ispits-epreuve-biologie-2024', title: 'Concours ISPITS — Biologie humaine & Soins', schoolId: 'ec-ispits-rabat', schoolName: 'ISPITS Rabat', organizationName: 'ISPITS Rabat', subject: 'SVT & Biologie', year: 2024, level: 'Bac+0', type: 'Concours', pages: 6, duration: '2h', downloads: 7260, hasCorrection: true, verificationStatus: 'VERIFIED', publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(35), updatedAt: daysAgo(2) },
];

export const SEED_DOCS: DocItem[] = [
  { id: 'd1', slug: 'cadre-referentiel-aref-2026', title: 'Cadre de référence officiel du concours des AREF (Enseignants)', category: 'Avis de concours', organizationName: "Ministère de l'Éducation Nationale", ministryId: 'min-education', competitionId: 'c1', year: 2026, description: 'Document officiel du MEN détaillant le nombre de postes par académie et les épreuves.', fileSize: '1,4 Mo', downloads: 15420, publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(6), updatedAt: daysAgo(1) },
  { id: 'd2', slug: 'guide-candidat-ensa-2026', title: 'Guide du candidat au concours commun ENSA Maroc 2026', category: 'Guide', organizationName: 'ENSA Marrakech', schoolId: 'ec-ensa-marrakech', competitionId: 'c13', year: 2026, description: 'Consignes de déroulement du concours commun ENSA et modalités d’affectation.', fileSize: '950 Ko', downloads: 9130, publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(9), updatedAt: daysAgo(2) },
  { id: 'd3', slug: 'notice-officielle-cnc-2026', title: 'Notice officielle du Concours National Commun (CNC) 2026', category: 'Notice officielle', organizationName: 'EMI — Réseau CNC', schoolId: 'ec-emi', competitionId: 'c14', year: 2026, description: 'Règlement du CNC pour les classes prépas scientifiques (filières MP, PSI, TSI).', fileSize: '2,8 Mo', downloads: 11670, publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(30), updatedAt: daysAgo(3) },
  { id: 'd4', slug: 'guide-tafem-encg-2026', title: 'Manuel de préparation au test TAFEM (ENCG Maroc)', category: 'Guide', organizationName: 'ENCG Settat', schoolId: 'ec-encg-settat', competitionId: 'c17', year: 2026, description: 'Exemples de questions types, structure des 4 sous-tests et conseils pour le jour J.', fileSize: '1,6 Mo', downloads: 14890, publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(20), updatedAt: daysAgo(2) },
  { id: 'd5', slug: 'arrete-ministeriel-fmp-2026', title: 'Arrêté ministériel relatif à l’accès aux Facultés de Médecine et Pharmacie', category: 'Texte juridique', organizationName: 'Facultés de Médecine du Maroc', schoolId: 'ec-fmpr', competitionId: 'c26', year: 2026, description: 'Conditions de diplôme, répartition des places par faculté et seuil de présélection.', fileSize: '780 Ko', downloads: 12210, publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(25), updatedAt: daysAgo(1) },
  { id: 'd6', slug: 'brochure-officielle-ispits-2026', title: 'Brochure des filières de formation dans les ISPITS du Maroc', category: 'Guide', organizationName: 'ISPITS Rabat', schoolId: 'ec-ispits-rabat', competitionId: 'c25', year: 2026, description: 'Présentation des 23 spécialités infirmières et des perspectives de carrière dans le secteur public.', fileSize: '2,1 Mo', downloads: 8340, publishStatus: 'PUBLISHED', isDemo: false, createdAt: daysAgo(18), updatedAt: daysAgo(5) },
];

export const SEED_COURSES: Course[] = [
  {
    id: 'course-maths',
    slug: 'mathematiques-concours-ingenieurs',
    title: 'Mathématiques — Concours d’ingénieurs (ENSA, ENSAM, CNC)',
    subject: 'Mathématiques',
    level: 'Bac / Bac+2',
    description: 'Programme intensif complet : suites, calcul différentiel, algèbre linéaire, probabilités et annales corrigées.',
    color: '#1565C0',
    duration: '28h',
    difficulty: 'Intermédiaire',
    publishStatus: 'PUBLISHED',
    isDemo: false,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
    chapters: [
      {
        id: 'ch-m1', title: 'Suites numériques et séries', order: 1, lessons: [
          { id: 'l-m1', title: 'Généralités, monotonie et convergence', type: 'VIDEO', duration: '45 min', content: 'Théorèmes fondamentaux de convergence et méthodes pour les questions à choix multiples.', order: 1 },
          { id: 'l-m2', title: 'Suites arithmétiques et géométriques', type: 'TEXT', duration: '30 min', content: 'Formules de somme et astuces d’identification rapide.', order: 2 },
          { id: 'l-m3', title: 'Annales ENSA corrigées — Suites', type: 'EXERCISE', duration: '1h', content: '25 exercices issus des concours ENSA des 5 dernières années.', order: 3 },
          { id: 'l-m4', title: 'QCM chronométré — Suites', type: 'QUIZ', duration: '25 min', content: 'Évaluation type concours.', order: 4 },
        ]
      },
      {
        id: 'ch-m2', title: 'Fonctions et calcul intégral', order: 2, lessons: [
          { id: 'l-m5', title: 'Continuité, dérivation et développements limités', type: 'VIDEO', duration: '50 min', content: 'Techniques de calcul rapide de limites indéterminées.', order: 1 },
          { id: 'l-m6', title: 'Calcul intégral et équations différentielles', type: 'TEXT', duration: '40 min', content: 'Intégration par parties, changement de variables et applications physiques.', order: 2 },
          { id: 'l-m7', title: 'Concours blanc complet', type: 'QUIZ', duration: '1h30', content: 'Sujet blanc conforme au format officiel ENSA.', order: 3 },
        ]
      },
    ],
  },
  {
    id: 'course-tafem',
    slug: 'tafem-prepa-complete',
    title: 'TAFEM — Préparation au concours commun des 12 ENCG',
    subject: 'Logique & Management',
    level: 'Baccalauréat',
    description: 'Entraînement complet aux 4 sous-tests du TAFEM : raisonnement logique, calcul mental rapide, culture générale et anglais.',
    color: '#E65100',
    duration: '22h',
    difficulty: 'Avancé',
    publishStatus: 'PUBLISHED',
    isDemo: false,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(2),
    chapters: [
      {
        id: 'ch-t1', title: 'Sous-test 1 & 2 : Logique et mathématiques', order: 1, lessons: [
          { id: 'l-t1', title: 'Astuces de calcul mental et pourcentages', type: 'VIDEO', duration: '40 min', content: 'Résoudre en moins de 45 secondes sans calculatrice.', order: 1 },
          { id: 'l-t2', title: 'Séries alphanumériques et dominos', type: 'EXERCISE', duration: '1h', content: 'Entraînement aux suites de figures et de nombres.', order: 2 },
        ]
      },
      {
        id: 'ch-t2', title: 'Sous-test 3 & 4 : Culture générale et Anglais', order: 2, lessons: [
          { id: 'l-t3', title: 'Fiches institutions et économie du Maroc', type: 'PDF', duration: '50 min', content: 'Faits marquants, géographie économique et actualité nationale.', order: 1 },
          { id: 'l-t4', title: 'Sujet blanc officiel TAFEM chronométré', type: 'QUIZ', duration: '2h', content: 'Simulation intégrale avec barème officiel (+3 / -1).', order: 2 },
        ]
      },
    ],
  },
  {
    id: 'course-cg',
    slug: 'culture-generale-institutions-maroc',
    title: 'Culture Générale & Institutions du Royaume du Maroc',
    subject: 'Culture Générale',
    level: 'Tous niveaux',
    description: 'Guide indispensable pour réussir les épreuves écrites et les entretiens oraux des ministères et grandes écoles.',
    color: '#1B5E20',
    duration: '14h',
    difficulty: 'Débutant',
    publishStatus: 'PUBLISHED',
    isDemo: false,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(7),
    chapters: [
      {
        id: 'ch-c1', title: 'Organisation constitutionnelle du Royaume', order: 1, lessons: [
          { id: 'l-c1', title: 'La Constitution de 2011 et les pouvoirs', type: 'TEXT', duration: '35 min', content: 'Rôles du Chef du Gouvernement, Parlement et Pouvoir Judiciaire.', order: 1 },
          { id: 'l-c2', title: 'Décentralisation et régionalisation avancée', type: 'VIDEO', duration: '40 min', content: 'Les 12 régions du Maroc et les compétences des collectivités.', order: 2 },
          { id: 'l-c3', title: 'Quiz — Institutions marocaines', type: 'QUIZ', duration: '20 min', content: '30 questions types des concours administratifs.', order: 3 },
        ]
      },
    ],
  },
];

export const SEED_USERS: User[] = [
  { id: 'u-admin', firstName: 'Admin', lastName: 'ConcoursMaroc', email: 'admin@concoursmaroc.ma', passwordHash: hashPassword('Admin123!'), role: 'ADMIN', status: 'ACTIVE', city: 'Rabat', createdAt: daysAgo(120), lastLoginAt: daysAgo(0) },
  { id: 'u-user', firstName: 'Yasmine', lastName: 'Bennani', email: 'user@example.ma', passwordHash: hashPassword('User1234!'), role: 'USER', status: 'ACTIVE', city: 'Marrakech', level: 'Baccalauréat', createdAt: daysAgo(30), lastLoginAt: daysAgo(1) },
];

export const SEED_NOTIFICATIONS: AppNotification[] = [
  { id: 'n1', userId: 'all', title: 'Concours ENSA Maroc 2026 ouvert', message: 'Les préinscriptions au concours commun des 12 ENSA du Maroc sont ouvertes sur le portail officiel.', type: 'info', link: '/concours/concours-ensa-maroc-1ere-annee-2026', readBy: [], createdAt: daysAgo(1) },
  { id: 'n2', userId: 'all', title: 'Date limite TAFEM ENCG 2026', message: 'Il vous reste 32 jours pour déposer votre dossier au concours commun d’accès aux ENCG.', type: 'deadline', link: '/concours/concours-tafem-encg-maroc-2026', readBy: [], createdAt: daysAgo(2) },
  { id: 'n3', userId: 'all', title: 'Annales officielles 2024 publiées', message: 'Le sujet et corrigé officiel FMP et ENSA 2024 sont désormais téléchargeables en PDF.', type: 'success', link: '/examens', readBy: [], createdAt: daysAgo(3) },
  { id: 'n4', userId: 'all', title: 'Recrutement Enseignants AREF', message: 'Le Ministère de l’Éducation Nationale a publié l’avis officiel pour 20 000 postes.', type: 'info', link: '/concours/concours-recrutement-enseignants-2026', readBy: [], createdAt: daysAgo(4) },
];
