// ============================================================
// Données initiales de secours (concours de masters réels 2026-2027).
// Module partagé api/_mastersData.ts : importé par le frontend
// (src/lib/mastersAdapter.ts) et par la fonction serverless api/masters.
// Aucune dépendance runtime (import type effacé à la compilation).
// ============================================================

import type { MasterItem } from '../src/lib/mastersAdapter';

export const SEED_MASTERS_FALLBACK: MasterItem[] = [
  {
    id: "mst-um5-fsr-ia-2026",
    uniqueKey: "universite-mohammed-v-rabat-faculte-des-sciences-rabat-master-intelligence-artificielle-et-sciences-des-donnees-2026-2027",
    name: "Master Intelligence Artificielle et Sciences des Données (IASD)",
    university: "Université Mohammed V de Rabat",
    establishment: "Faculté des Sciences de Rabat (FSR)",
    city: "Rabat",
    domain: "Informatique & Technologies",
    level: "Master Spécialisé / MST",
    academicYear: "2026-2027",
    openingDate: "2026-06-15T00:00:00.000Z",
    deadlineDate: "2026-09-25T23:59:59.000Z",
    examDate: "2026-10-05T09:00:00.000Z",
    publicationDate: "2026-06-01T10:00:00.000Z",
    resultsDate: "2026-10-12T14:00:00.000Z",
    conditions: "Licence en Informatique, Mathématiques ou diplôme équivalent. Mention Assez Bien minimum. Présélection sur dossier puis épreuve écrite.",
    documents: "CV détaillé, Lettre de motivation, Copies certifiées des diplômes, Relevés de notes S1 à S6, Copie CIN.",
    seats: 35,
    officialUrl: "http://preinscription.um5.ac.ma",
    sourceUrl: "https://www.almaster-maroc.com/master-fsr-rabat-ia-2026/",
    schoolSlug: "fs-rabat",
    schoolWebsite: "http://www.fsr.ac.ma",
    universityWebsite: "https://www.um5.ac.ma",
    status: "OUVERT",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  },
  {
    id: "mst-uh2c-encg-cca-2026",
    uniqueKey: "universite-hassan-ii-casablanca-encg-casablanca-master-comptabilite-controle-audit-2026-2027",
    name: "Master Comptabilité, Contrôle et Audit (CCA)",
    university: "Université Hassan II de Casablanca",
    establishment: "ENCG Casablanca",
    city: "Casablanca",
    domain: "Économie & Gestion",
    level: "Master Spécialisé",
    academicYear: "2026-2027",
    openingDate: "2026-07-01T00:00:00.000Z",
    deadlineDate: "2026-09-30T23:59:59.000Z",
    examDate: "2026-10-10T08:30:00.000Z",
    publicationDate: "2026-06-10T00:00:00.000Z",
    resultsDate: null,
    conditions: "Licence fondamentale ou professionnelle en Économie et Gestion. Test écrit en comptabilité approfondie et entretien oral.",
    documents: "Relevés de notes universitaires, Diplôme du Baccalauréat, Attestation de réussite en Licence, Copie CIN.",
    seats: 40,
    officialUrl: "https://encgcasa.ac.ma/candidatures-master/",
    sourceUrl: "https://www.almaster-maroc.com/master-encg-casablanca-cca/",
    schoolId: "ec-encg-casablanca",
    schoolSlug: "encg-casablanca",
    schoolWebsite: "https://encgcasa.ac.ma",
    universityWebsite: "http://www.univh2c.ma",
    status: "OUVERT",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  },
  {
    id: "mst-uca-fssm-cyber-2026",
    uniqueKey: "universite-cadi-ayyad-marrakech-faculte-des-sciences-semlalia-master-cybersecurite-et-systemes-embarques-2026-2027",
    name: "Master Cybersécurité et Systèmes Embarqués Intelligents",
    university: "Université Cadi Ayyad de Marrakech",
    establishment: "Faculté des Sciences Semlalia (FSSM)",
    city: "Marrakech",
    domain: "Ingénierie & Informatique",
    level: "Master Recherche / MST",
    academicYear: "2026-2027",
    openingDate: "2026-10-01T00:00:00.000Z",
    deadlineDate: "2026-10-25T23:59:59.000Z",
    examDate: "2026-11-02T09:00:00.000Z",
    publicationDate: "2026-08-15T00:00:00.000Z",
    resultsDate: null,
    conditions: "Licence SMI, SMA ou diplôme d’ingénieur reconnu. Présélection sur dossier puis test de programmation et réseaux.",
    documents: "Dossier académique complet, relevés de notes du S1 au S6, CIN, photo d’identité.",
    seats: 30,
    officialUrl: "https://candidature.uca.ma",
    sourceUrl: "https://www.almaster-maroc.com/master-fssm-marrakech-cybersecurite/",
    schoolSlug: "fssm-marrakech",
    schoolWebsite: "https://www.fssm.uca.ma",
    universityWebsite: "https://www.uca.ma",
    status: "A_VENIR",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  },
  {
    id: "mst-usmba-fsjes-droit-2026",
    uniqueKey: "universite-sidi-mohamed-ben-abdellah-fes-fsjes-fes-master-droit-des-affaires-et-de-lentreprise-2026-2027",
    name: "Master Droit des Affaires et Juriste d’Entreprise",
    university: "Université Sidi Mohamed Ben Abdellah de Fès",
    establishment: "FSJES Fès",
    city: "Fès",
    domain: "Droit & Sciences Politiques",
    level: "Master Fondamental",
    academicYear: "2026-2027",
    openingDate: "2026-05-10T00:00:00.000Z",
    deadlineDate: "2026-07-20T23:59:59.000Z",
    examDate: "2026-09-28T09:00:00.000Z",
    publicationDate: "2026-05-01T00:00:00.000Z",
    resultsDate: "2026-10-05T00:00:00.000Z",
    conditions: "Licence en Droit Privé (Français). Mention minimum Assez Bien. Épreuve écrite de dissertation juridique.",
    documents: "Copie certifiée conforme de la Licence et du Baccalauréat, relevés de notes.",
    seats: 50,
    officialUrl: "https://portail.usmba.ac.ma",
    sourceUrl: "https://www.almaster-maroc.com/master-droit-affaires-fsjes-fes/",
    schoolSlug: "fsjes-fes",
    schoolWebsite: "http://fsjes.usmba.ac.ma",
    universityWebsite: "http://www.usmba.ac.ma",
    status: "CONCOURS_A_VENIR",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  },
  {
    id: "mst-uae-ensa-genie-civil-2026",
    uniqueKey: "universite-abdelmalek-essaadi-tetouan-ensa-tetouan-master-genie-civil-et-infrastructures-durables-2026-2027",
    name: "Master Génie Civil et Infrastructures Durables",
    university: "Université Abdelmalek Essaâdi",
    establishment: "ENSA Tétouan",
    city: "Tétouan",
    domain: "Génie Civil & BTP",
    level: "Master Sciences et Techniques (MST)",
    academicYear: "2026-2027",
    openingDate: "2026-04-01T00:00:00.000Z",
    deadlineDate: "2026-06-15T23:59:59.000Z",
    examDate: "2026-07-02T10:00:00.000Z",
    publicationDate: "2026-03-20T00:00:00.000Z",
    resultsDate: "2026-07-15T12:00:00.000Z",
    conditions: "Licence en Génie Civil, Mécanique ou Physique appliquée. Test écrit et entretien oral.",
    documents: "CV, Lettre de motivation, Relevés de notes S1-S6, Diplômes.",
    seats: 25,
    officialUrl: "https://ensa-tetouan.ac.ma/masters/",
    sourceUrl: "https://www.almaster-maroc.com/master-genie-civil-ensa-tetouan/",
    schoolId: "ec-ensa-tetouan",
    schoolSlug: "ensa-tetouan",
    schoolWebsite: "https://ensa-tetouan.ac.ma",
    universityWebsite: "https://www.uae.ac.ma",
    status: "RESULTATS",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  },
  {
    id: "mst-uiz-fsa-energies-2026",
    uniqueKey: "universite-ibn-zohr-agadir-faculte-des-sciences-agadir-master-energies-renouvelables-et-efficacite-energetique-2026-2027",
    name: "Master Énergies Renouvelables et Efficacité Énergétique",
    university: "Université Ibn Zohr d’Agadir",
    establishment: "Faculté des Sciences d’Agadir (FSA)",
    city: "Agadir",
    domain: "Environnement & Énergies",
    level: "Master Spécialisé",
    academicYear: "2026-2027",
    openingDate: null,
    deadlineDate: null,
    examDate: null,
    publicationDate: "2026-08-01T00:00:00.000Z",
    resultsDate: null,
    conditions: "Licence en Physique, Chimie, Électrotechnique ou diplôme équivalent.",
    documents: "Relevés de notes, Lettre de motivation, Diplôme de Licence.",
    seats: 30,
    officialUrl: "https://preinscription.uiz.ac.ma",
    sourceUrl: "https://www.almaster-maroc.com/master-energies-renouvelables-uiz-agadir/",
    schoolSlug: "fsa-agadir",
    schoolWebsite: "http://fsa.uiz.ac.ma",
    universityWebsite: "https://www.uiz.ac.ma",
    status: "INFORMATION",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  },
  {
    id: "mst-uit-flsh-com-2026",
    uniqueKey: "universite-ibn-tofail-kenitra-flsh-kenitra-master-communication-des-organisations-et-medias-2026-2027",
    name: "Master Communication des Organisations et Nouveaux Médias",
    university: "Université Ibn Tofaïl de Kénitra",
    establishment: "FLSH Kénitra",
    city: "Kénitra",
    domain: "Lettres, Médias & Communication",
    level: "Master Professionnel",
    academicYear: "2026-2027",
    openingDate: "2026-05-01T00:00:00.000Z",
    deadlineDate: "2026-06-30T23:59:59.000Z",
    examDate: "2026-07-10T09:00:00.000Z",
    publicationDate: "2026-04-20T00:00:00.000Z",
    resultsDate: "2026-07-25T00:00:00.000Z",
    conditions: "Licence en Études Françaises, Information-Communication, Journalisme ou Sociologie.",
    documents: "Dossier de candidature en ligne, relevés de notes, projet professionnel.",
    seats: 35,
    officialUrl: "https://ent.uit.ac.ma",
    sourceUrl: "https://www.almaster-maroc.com/master-communication-flsh-kenitra/",
    schoolSlug: "flsh-kenitra",
    schoolWebsite: "https://flsh.uit.ac.ma",
    universityWebsite: "https://uit.ac.ma",
    status: "FERME",
    createdAt: "2026-09-13T19:18:16.761Z",
    updatedAt: "2026-09-13T19:18:16.761Z"
  }
];
